#ifndef PROCESS_STATUS_HPP
#define PROCESS_STATUS_HPP

#include <cstdint>


enum class ProcessStatus : uint8_t{
    ACCEPTED,
    REJECTED_DUPLICATE_ID,
    REJECTED_ZERO_QUANTITY,
    REJECTED_INVALID_PRICE,
    REJECTED_QUANTITY_TOO_LARGE,
    REJECTED_CAPACITY,
    PARTIALLY_FILLED_CAPACITY,
    REJECTED_INVALID_SIDE
};

#endif // PROCESS_STATUS_HPP